services:
  xnet-mysql:
    image: mysql:8.4.4
    container_name: xnet-mysql
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volume/mysql:/var/lib/mysql
